### ISSUE TITLE
Failed to initialize WASM code

### ISSUE THREAD

**Issue by GuangTianLi** [solo-io/wasme#163]
wasme version 0.0.26
 
When I deploy on Istio 1.6.7, I get this error from the istio-proxy container:

```
[Envoy (Epoch 0)] [2020-08-25 06:06:05.299][21][warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:87] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 172.22.3.186_8000: Failed to initialize WASM code from /var/local/lib/wasme-cache/3f319eec32afdfb1c053e1aea3a665504ff9d5f5ea4019146bcb455dfaea29d1
virtualInbound: Failed to initialize WASM code from /var/local/lib/wasme-cache/3f319eec32afdfb1c053e1aea3a665504ff9d5f5ea4019146bcb455dfaea29d1
```

**Comment by Sodman** [comment]
Hi @GuangTianLi , did you create this filter yourself with `wasme init`? I just want to confirm that the filter being deployed is compatible with this version of Istio.  Are you using cpp or assemblyscript for this filter?

**Comment by GuangTianLi** [comment]
Istio version is 1.5.9.

I used proxy-wasm-rust-sdk to build my wasm.  Is there a compatibility issus about this filter?

**Comment by Sodman** [comment]
When you say you got an invalid path in the logs, do you mean the same error message as you reported in your first comment? Because that doesn't look like a path error to me, it looks like the module code couldn't be loaded which could be either compile errors in the filter itself, or possibly an incompatible version (very possible with the rust sdk). So this could be something different if it's now saying there's an invalid path.

Both assemblyscript and c++ filters definitely work with Istio 1.5.x and 1.6.x. We are also actively working on getting assemblyscript support for Istio 1.7 very soon.

Are you deploying to istio with `wasme deploy` or are you using `FilterDeployment` resources?

**Comment by GuangTianLi** [comment]
It does work, when I use `assemblyscript@0.9.1` and `@solo-io/proxy-runtime@0.1.1` which is used in `wasme init` rather than latest version.

**Comment by Sodman** [comment]
That explains it, `"@solo-io/proxy-runtime": "^0.1.8",` is the latest release of the assemblyscript runtime and is specifically compatible with the ABI used by Istio 1.7, which has had breaking changes since the version used by 1.6.

Marking this issue as resolved, let us know if you run into any other issues!
