### ISSUE TITLE
the --name option not recognized by wasme

### ISSUE THREAD

**Issue by mbanikazemi** [solo-io/wasme#93]
Here is an example:

$  wasme deploy istio  --id banix --namespace default --name helloworld-v1
Error: unknown flag: --name

**Comment by yuval-k** [comment]
the reason that name is not supported is because we use istio's [EnvoyFilter CRD](https://istio.io/docs/reference/config/networking/envoy-filter/) to instruct istio to inject our filter. 
That CRD has a workloadSelector that allows selecting pods by labels. AFAIK there is no way to create an EnvoyFilter CRD that will attach to a specific  pod.

**Comment by ilackarms** [comment]
@mbanikazemi the documentation for the command is incorrect, you want to use `--labels` instead. let me update that

**Comment by sriramcms** [comment]
Yes this  worked for me   =   --labels "app=details" , for adding filter to the details pods  in the istio bookinfo example.

**Comment by yuval-k** [comment]
closing as answered
